"""Main module for generating fake data."""

import logging
import secrets

from mimesis import Generic, Locale

from .config import DataFakerConfig
from .random_context import RandomContext


class DataFaker:
    """Class for abstract Faker methods."""

    def __init__(self, config: DataFakerConfig):
        """Initialize DataFaker."""
        self.logger = logging.getLogger(self.__class__.__name__)
        self.seed = config.seed
        self.logger.info(f"DataFaker seed: {self.seed}")
        self.random = RandomContext(self.seed)
        self.api = Generic(locale=Locale.EN, seed=self.seed)
        self.locale: dict[Locale, Generic] = {}
        if config.locales:
            self.locale = {loc: Generic(locale=loc, seed=self.seed) for loc in config.locales}

    def add_locale(self, loc: Locale) -> None:
        """
        Add locale.

        :param locale: locale to add
        :return: None
        """
        if not loc:
            return
        self.locale[loc] = Generic(locale=loc, seed=self.seed)

    def docker_string(self, separator: str = "_") -> str:
        """
        Get random Docker-style name.

        :param separator: separator between words ('_')
        :returns
        """
        left = {
            "admiring",
            "adoring",
            "affectionate",
            "agitated",
            "amazing",
            "angry",
            "awesome",
            "blissful",
            "boring",
            "brave",
            "clever",
            "cocky",
            "compassionate",
            "competent",
            "condescending",
            "confident",
            "cranky",
            "dazzling",
            "determined",
            "distracted",
            "dreamy",
            "eager",
            "ecstatic",
            "elated",
            "elegant",
            "epic",
            "fervent",
            "festive",
            "flamboyant",
            "focused",
            "friendly",
            "frosty",
            "gallant",
            "gifted",
            "goofy",
            "gracious",
            "happy",
            "hardcore",
            "heuristic",
            "hopeful",
            "hungry",
            "infallible",
            "inspiring",
            "jolly",
            "jovial",
            "keen",
            "kind",
            "laughing",
            "loving",
            "lucid",
            "mystifying",
            "modest",
            "musing",
            "naughty",
            "nervous",
            "nifty",
            "nostalgic",
            "objective",
            "optimistic",
            "peaceful",
            "pedantic",
            "pensive",
            "practical",
            "priceless",
            "quirky",
            "quizzical",
            "recursing",
            "relaxed",
            "reverent",
            "romantic",
            "sad",
            "serene",
            "sharp",
            "silly",
            "sleepy",
            "stoic",
            "stupefied",
            "suspicious",
            "sweet",
            "tender",
            "thirsty",
            "trusting",
            "unruffled",
            "upbeat",
            "vibrant",
            "vigilant",
            "vigorous",
            "wizardly",
            "wonderful",
            "xenodochial",
            "youthful",
            "zealous",
            "zen",
        }

        right = {
            "albattani",
            "allen",
            "almeida",
            "archimedes",
            "ardinghelli",
            "aryabhata",
            "austin",
            "babbage",
            "banach",
            "banzai",
            "bardeen",
            "bartik",
            "bassi",
            "beaver",
            "bell",
            "benz",
            "bhabha",
            "bhaskara",
            "black",
            "blackburn",
            "blackwell",
            "bohr",
            "booth",
            "borg",
            "bose",
            "bouman",
            "boyd",
            "brahmagupta",
            "brattain",
            "brown",
            "buck",
            "burnell",
            "cannon",
            "carson",
            "cartwright",
            "cerf",
            "chandrasekhar",
            "chaplygin",
            "chatelet",
            "chatterjee",
            "chebyshev",
            "cohen",
            "chaum",
            "clarke",
            "colden",
            "cori",
            "cray",
            "curie",
            "darwin",
            "davinci",
            "dijkstra",
            "dubinsky",
            "easley",
            "edison",
            "einstein",
            "elbakyan",
            "elgamal",
            "elion",
            "ellis",
            "engelbart",
            "euclid",
            "euler",
            "faraday",
            "feistel",
            "fermat",
            "fermi",
            "feynman",
            "franklin",
            "gagarin",
            "galileo",
            "galois",
            "ganguly",
            "gates",
            "gauss",
            "germain",
            "goldberg",
            "goldstine",
            "goldwasser",
            "golick",
            "goodall",
            "gould",
            "greider",
            "grothendieck",
            "haibt",
            "hamilton",
            "haslett",
            "hawking",
            "hellman",
            "heisenberg",
            "hermann",
            "herschel",
            "hertz",
            "heyrovsky",
            "hodgkin",
            "hoover",
            "hopper",
            "hugle",
            "hypatia",
            "ishizaka",
            "jackson",
            "jang",
            "jennings",
            "jepsen",
            "johnson",
            "joliot",
            "jones",
            "kalam",
            "kapitsa",
            "kare",
            "keldysh",
            "keller",
            "kepler",
            "khayyam",
            "khorana",
            "kilby",
            "kirch",
            "knuth",
            "kowalevski",
            "lalande",
            "lamarr",
            "lamport",
            "leakey",
            "leavitt",
            "lederberg",
            "lehmann",
            "lewin",
            "lichterman",
            "liskov",
            "lovelace",
            "lumiere",
            "mahavira",
            "margulis",
            "matsumoto",
            "maxwell",
            "mayer",
            "mccarthy",
            "mcclintock",
            "mclaren",
            "mclean",
            "mcnulty",
            "meitner",
            "meninsky",
            "mestorf",
            "mirzakhani",
            "morse",
            "murdock",
            "newton",
            "nightingale",
            "nobel",
            "noether",
            "northcutt",
            "noyce",
            "panini",
            "pare",
            "pasteur",
            "payne",
            "perlman",
            "pike",
            "poincare",
            "poitras",
            "ptolemy",
            "raman",
            "ramanujan",
            "ride",
            "montalcini",
            "ritchie",
            "roentgen",
            "rosalind",
            "saha",
            "sammet",
            "sanderson",
            "shannon",
            "shaw",
            "shirley",
            "shockley",
            "shtern",
            "sinoussi",
            "snyder",
            "solomon",
            "spence",
            "stallman",
            "stonebraker",
            "sutherland",
            "swanson",
            "swartz",
            "swirles",
            "taussig",
            "tereshkova",
            "tesla",
            "tharp",
            "thompson",
            "torvalds",
            "tu",
            "turing",
            "varahamihira",
            "visvesvaraya",
            "volhard",
            "villani",
            "wescoff",
            "wilbur",
            "wiles",
            "williams",
            "williamson",
            "wilson",
            "wing",
            "wozniak",
            "wright",
            "wu",
            "yalow",
            "yonath",
            "kaspersky",
        }

        adj = self.random.choice(sorted(left))
        name = self.random.choice(sorted(right))
        return f"{adj}{separator}{name}"

    def token_urlsafe(self, length: int = 16):
        """Generate a cryptographically secure random token."""
        return secrets.token_urlsafe(length)
